version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432"
    volumes:
      - /usr/data/volumes/pgdata/etc:/etc/postgresql
      - /usr/data/volumes/pgdata/log:/var/log/postgresql
      - /usr/data/volumes/pgdata/data:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - /usr/data/volumes/bundle:/bundle
    ports:
      - "3000:3000"
    environment:
      - BUNDLE_PATH=/bundle
    depends_on:
      - db
