# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4b2050460d5782d20c29c625a16e7763c8b4cf02a9b1627d18c547986432e5501d4155862278c3e444ebef5a449ced031db72959c47bb7858a4d134ef48b479f

test:
  secret_key_base: 13e0b478a63c7a892e6e04180961094f3c0c6fe37be5ac7dde0187882e59cbde3c1f0d4afa709386f27dc023bf8e54a344a4ce8c74fe770fd685eaf236c5225d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
